tenant: opsera
app_name: simpson
cloud_provider: aws
region: us-west-2
region_short: usw2

clusters:
  hub: argocd-usw2
  spoke: opsera-usw2-np
  argocd_server: argocd-usw2.agent.opsera.dev

environments:
  - name: dev
    namespace: opsera-simpson-dev
    deployment_strategy: rolling
    replicas: 2
    branch: main

ecr:
  repository: opsera/simpson
  region: us-west-2

integrations:
  gitleaks:
    enabled: true
  grype:
    enabled: true
    mode: warn
