apiVersion: v1
kind: Service
metadata:
  name: hb2
  namespace: opsera-hb2-dev
  labels:
    app: hb2
    tenant: opsera
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hb2
