apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simp123
  labels:
    app: simp123
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: simp123.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simp123
                port:
                  number: 80
  tls:
    - hosts:
        - simp123.agent.opsera.dev
      secretName: simp123-tls
