apiVersion: v1
kind: Service
metadata:
  name: hb1
  namespace: opsera-hb1-dev
  labels:
    app: hb1
    tenant: opsera
spec:
  type: ClusterIP
  selector:
    app: hb1
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
