apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-hb2-dev
  namespace: argocd
  labels:
    tenant: opsera
    app: hb2
    environment: dev
    managed-by: opsera-c2c
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-test-org/simplecore-app.git
    targetRevision: main
    path: .opsera-hb2/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-hb2-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
