apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-simpson-staging

resources:
  - ../../base
  - rollout-bluegreen.yaml
  - services-bluegreen.yaml
  - ingress.yaml

images:
  - name: simpson
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/simpson
    newTag: staging-latest

labels:
  - pairs:
      environment: staging
    includeSelectors: false

# ENVIRONMENT is set via env var in rollout-bluegreen.yaml
