apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-hb1-dev

resources:
- ../../base

labels:
- pairs:
    environment: dev
    managed-by: opsera-c2c

images:
- name: hb1
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/hb1
  newTag: 8eb5ef8-20260214115746

configMapGenerator:
- behavior: merge
  literals:
  - ENVIRONMENT=dev
  name: hb1-config

replicas:
- count: 2
  name: hb1
