apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-simpson-dev

resources:
  - ../../base
  - deployment.yaml
  - service.yaml

images:
  - name: simpson
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/simpson
    newTag: dev-3feb48df-20260214041347

labels:
  - pairs:
      environment: dev
    includeSelectors: false
