apiVersion: v1
kind: Service
metadata:
  name: simpson
  namespace: opsera-simpson-dev
  labels:
    app: simpson
    tenant: opsera
spec:
  type: ClusterIP
  selector:
    app: simpson
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
