apiVersion: v1
kind: Service
metadata:
  name: simplecore14
  labels:
    app: simplecore14
    tenant: opsera
    managed-by: opsera-c2c
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: simplecore14
