apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-simpson-qa

resources:
  - rollout-canary.yaml
  - services-canary.yaml
  - analysis-template.yaml
  - ingress.yaml

images:
  - name: simpson
    newName: PLACEHOLDER_ECR_URI/simpson
    newTag: latest

labels:
  - pairs:
      environment: qa
    includeSelectors: false

# ConfigMap for QA environment
configMapGenerator:
  - name: simpson-config
    behavior: merge
    literals:
      - ENVIRONMENT=qa
      - LOG_LEVEL=info
