apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-simpson-qa

resources:
  - ../../base
  - rollout-canary.yaml
  - services-canary.yaml
  - analysis-template.yaml
  - ingress.yaml

images:
  - name: simpson
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/simpson
    newTag: qa-0182f40a-20260214050303

labels:
  - pairs:
      environment: qa
    includeSelectors: false

# ENVIRONMENT is set via env var in rollout-canary.yaml
# No need for ConfigMap override
