apiVersion: v1
kind: Service
metadata:
  name: simplecore-app
  namespace: opsera-simplecore-app-dev
  labels:
    app: simplecore-app
spec:
  type: ClusterIP
  selector:
    app: simplecore-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
