apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-hb2-dev

resources:
- ../../base

labels:
- pairs:
    app: hb2
    environment: dev
    managed-by: opsera-c2c
    tenant: opsera

images:
- name: hb2
  newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/hb2
  newTag: 8eb5ef8-20260214115747

replicas:
- count: 2
  name: hb2
