apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-simpcore1-dev

resources:
  - ../../base
  - deployment.yaml
  - service.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/simpcore1
    newTag: 10be19f-20260214101630 

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      managed-by: opsera-c2c

commonAnnotations:
  managed-by: opsera-code-to-cloud
  environment: dev
